{{- if .Values.istio.enabled}}
{{- if .Values.splitService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: canary-{{ include "canary-service.fullname" . }}
  labels:
    {{- include "canary-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "canary-service.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
