{{- if .Values.istio.enabled }}
{{- if .Values.splitService.enabled }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "canary-service.fullname" . }}
  labels:
    {{- include "canary-service.labels" . | nindent 4 }}
spec:
  gateways:
    - {{- include "canary-service.fullname" }}
  http:
    - name: canary
      match:
        - uri:
            {{- if  .Values.splitHost.enabled }}
            prefix: /
            {{- else }}
            prefix: /canary/
            {{- end }}
      rewrite:
        uri: /
      route:
        - destination:
            host: stable-{{- include "canary-service.fullname" }}.{{ .Release.Namespace }}.svc.cluster.local
{{- end }}
{{- end }}
