{{- if .Values.istio.enabled }}
{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ include "canary-service.fullname" . }}
  labels:
    {{- include "canary-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "canary-service.selectorLabels" . | nindent 4 }}
  servers:
    - hosts:
        - {{ .Values.gateway.host | include "canary-service.fullname" . }}-{{ .Values.gateway.domain }}
        {{- if .Values.splitHost.enabled }}
        - stable-{{ .Values.gateway.host | include "canary-service.fullname" . }}-{{ .Values.gateway.domain }}
        - canary-{{ .Values.gateway.host | include "canary-service.fullname" . }}-{{ .Values.gateway.domain }}
        {{- end }}
      port:
        {{- if .Values.gateway.https }}
        number: 443
        name: https
        protocol: HTTP
        {{- else }}
        number: 80
        name: http
        protocol: HTTP
        {{- end }}
{{- end }}
{{- end }}
