name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install helm-docs
        run: |
          go install github.com/norwoodj/helm-docs/cmd/helm-docs@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Generate Helm Docs
        run: helm-docs

      - name: Generate CHANGELOG.md
        run: |
          echo "# Changelog" > CHANGELOG.md
          git log --pretty=format:"- %s (%h)" > temp.log
          cat temp.log >> CHANGELOG.md
          rm temp.log

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add charts/**/README.md CHANGELOG.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(docs): update README and CHANGELOG"
            git push
          fi
